<?php
/**
 * @file
 * Code for the Ktopic Review feature.
 */

include_once 'ktopic_review.features.inc';

// Turn '/<ktopic>-review' into 'node/%node'
/*
function ktopic_review_url_inbound_alter(&$path, $original_path, $path_language) {

  //dsm($path, 'path');
  //dsm($original_path, 'original_path');
  //dsm($path_language, 'path_language');

  if ($ktopic = ktopic_review_ktopic_from_path($original_path, $path_language)) {
    if ($kreview = ktopic_review_ktopic_get_last_review($ktopic)) {
      $path = entity_uri('node', $kreview)['path'];
    }

    // @todo Disable globalredirect for this path.
    // @issue https://www.drupal.org/node/1438584
    // @test Have tried. Don't know if I really need it.

  }
}
*/

/**
 * @implements hook_node_info_alter().
 */
function ktopic_review_node_info_alter(&$items) {
  //$items['kreview']['base'] = 'ktopic_review';
}

/**
 * @implements hook_node_insert().
 */
function ktopic_review_node_insert($node) {
  ktopic_review_update_path_alias($node);
}

/**
 * @implements hook_node_update().
 */
function ktopic_review_node_update($node) {
  ktopic_review_update_path_alias($node);
}

// Assign the /<ktopic>-review alias to the latest node<kreview>.
// If it's published and creation date is the latest.
function ktopic_review_update_path_alias($node) {
  if ($node->type == 'kreview') {
    if ($node->status == NODE_PUBLISHED) {
      $kreviews = ktopic_review_get_reviews();

    }
  }
}

/**
 * Try to fetch a node<ktopic> with the request path.
 */
function ktopic_review_ktopic_from_path($path, $lang) {
  $ktopic = NULL;
  $check = '-review';
  if (KtoolsString::endsWith($path, $check)) {
    $ktopic_name = substr_replace($path, '', -strlen($check));
    $conds[] = array(
      'column' => 'machine',
      'value' => $ktopic_name,
      'operator' => '=',
    );
    $ktopics = KtoolsEntityField::queryEntities('field_ktopic_name', $conds, 'node', TRUE, $lang);
    $ktopic = reset($ktopics);
  }

  return $ktopic;
}

// Fetch all reviews of this topic.
function ktopic_review_ktopic_get_reviews($ktopic) {
  $lang = entity_language('node', $ktopic);
  // og use site default language instead, it would be en.
  if ($lang == LANGUAGE_NONE) {
    $lang = language_default('language');
  }
  $kreviews = KtoolsEntityField::entityreferenceRevertEntities('og_ktopic_ref', $ktopic->nid, 'node', TRUE, $lang);

  return $kreviews;
}

/**
 * Try to fetch the latest node<kreview> for the specific node<ktopic>.
 */
function ktopic_review_ktopic_get_last_review($ktopic) {
  $kreview = NULL;
  $kreviews = ktopic_review_ktopic_get_reviews($ktopic);
  $timestamp = 0;
  foreach ($kreviews as $kreview_tmp) {
    // @issue May need to consider nid if timestamp is the same.
    if ($kreview_tmp->status == NODE_PUBLISHED && $kreview_tmp->created > $timestamp) {
      $timestamp = $kreview_tmp->created;
      $kreview = $kreview_tmp;
    }
  }

  return $kreview;
}

function ktopic_review_kreview_is_last_review($kreview) {
  $ktopic = ktopic_review_kreview_get_topic($kreview);
  $kreview_last = ktopic_review_ktopic_get_last_review($ktopic);

  return $kreview->nid == $kreview_last->nid ? TRUE : FALSE;
}

// Fetch the host topic.
function ktopic_review_kreview_get_topic($kreview) {
  $lang = entity_language('node', $kreview);

  return node_load($kreview->og_ktopic_ref[$lang][0]);
}

// Fetch related reviews.
function ktopic_review_kreview_get_reviews($kreview) {
  $ktopic = ktopic_review_kreview_get_topic($kreview);

  return ktopic_review_ktopic_get_reviews($ktopic);
}
