<?php
/**
 * @file
 * Code for the Ktopic Review feature.
 */

include_once 'ktopic_review.features.inc';

// Turn '/<ktopic>-review' into 'node/%node'
function ktopic_review_url_inbound_alter(&$path, $original_path, $path_language) {
  /*
  dsm($path, 'path');
  dsm($original_path, 'original_path');
  dsm($path_language, 'path_language');
  */
  if ($ktopic = ktopic_review_get_topic($original_path, $path_language)) {
    if ($kreview = ktopic_review_get_review_last($ktopic, $path_language)) {
      $path = entity_uri('node', $kreview)['path'];
    }
    // @todo Disable globalredirect for this path.
    // @issue https://www.drupal.org/node/1438584
    // @test Have tried. Don't know if I really need it.
  }
}

function ktopic_review_get_topic($path, $language) {
  $ktopic = NULL;
  $check = '-review';
  if (KtoolsString::endsWith($path, $check)) {
    $ktopic_name = substr_replace($path, '', -strlen($check));
    $conds[] = array(
      'column' => 'machine',
      'value' => $ktopic_name,
      'operator' => '=',
    );
    $ktopic_ids = KtoolsEntityField::queryEntities('field_ktopic_name', $conds, 'node', $language);
    $ktopic_id = reset($ktopic_ids);
    $ktopic = node_load($ktopic_id);
  }

  return $ktopic;
}

function ktopic_review_get_review_last($ktopic, $language) {
  $kreview = NULL;

  $kreview_ids = KtoolsEntityField::entityreferenceRevertEntities('og_ktopic_ref', $ktopic->nid, 'node', $language);
  $kreview_id = reset($kreview_ids);
  if ($kreview_id) {
    $kreview = node_load($kreview_id);
  }

  return $kreview;
}
